class AppRoutes {
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const logIn = '/login';
  static const signup = '/signup';
  static const specialistSignup = '/specialistSignup';
  static const forgetPassword = '/forgetPassword';
  static const otp = '/otp';
  static const createNewPassword = '/createNewPassword';
  static const successPage = '/successPage';
  static const waitingForApproval = '/waitingForApproval';
  static const specialistSelection = '/specialistSelection';
  static const fillQuestionnaireOrSkip = '/fillQuestionnaireOrSkip';
  static const questionnaire = '/questionnaire';
  static const matchTherapist = '/matchTherapist';
  static const specialistList = '/specialistList';
  static const specialistView = '/specialistView'; // Unified specialist view page
  static const specialistDetail = '/specialistDetail'; // Deprecated - use specialistView
  static const specialistViewProfile = '/specialistViewProfile'; // Deprecated - use specialistView
  static const specialistApproval = '/specialistApproval';
  static const profile = '/profile';
  static const editProfile = '/editProfile';
  static const bookConsultation = '/bookConsultation';
  static const paymentSummary = '/paymentSummary';
  static const paymentDetails = '/paymentDetails';
  static const payNow = '/payNow';
  static const navScreen = '/navScreen';
  static const patientHome = '/patientHome';
  static const pharmacy = '/pharmacy';
  static const medicineDetail = '/medicineDetail';
  static const cart = '/cart';
  static const checkout = '/checkout';
  static const orderConfirmation = '/orderConfirmation';
  static const orderTracking = '/orderTracking';
  static const recentPatientsList = '/recentPatientsList';
  static const recentPatientConsultationHistory = '/recentPatientConsultationHistory';
  static const viewConsultationNotes = '/viewConsultationNotes';
  static const adminPatients = '/adminPatients';
  static const adminPatientDetails = '/adminPatientDetails';
  static const adminPatientProfileView = '/adminPatientProfileView';
  static const videoCall = '/videoCall';
  static const adminSessions = '/adminSessions';
  static const sessionDetails = '/sessionDetails';
  static const rescheduleSession = '/rescheduleSession';
  static const pharmacyOrders = '/pharmacyOrders';
  static const orderDetail = '/orderDetail';
  static const orderPrescription = '/orderPrescription';
  static const adminManageAdBannerPage = '/adminManageAdBannerPage';
  static const adminAdBannerCreationPage = '/adminAdBannerCreationPage';
  static const adminManageFeatureProductPage = '/adminManageFeatureProductPage';
  static const adminAddFeaturedProductPage = '/adminAddFeaturedProductPage';
  static const adminMedicineProductListingPage = '/adminMedicineProductListingPage';
  static const adminMedicineOrdersPage = '/adminMedicineOrdersPage';
  static const adminMedicineAddProductPage = '/adminMedicineAddProductPage';
  static const adminGlobalSessionDiscountPage = '/adminGlobalSessionDiscountPage';
  static const adminOrderDetailsPage = '/adminOrderDetailsPage';
  static const paymentHistory = '/paymentHistory';
}
